spring:
  config:
    activate:
      on-profile: prod
      
  datasource:
    url: jdbc:sqlserver://expensetracker-sql.database.windows.net:1433;database=expense-tracker-db;encrypt=true;trustServerCertificate=false;loginTimeout=30;
    username: sqladmin@expensetracker-sql
    password: ${DB_PASS}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update # Creates/updates tables automatically
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  sql:
    init:
      mode: never

# JWT configuration
jwt:
  secret: ${JWT_SECRET}  # Read from Azure App Settings or .env
  expiration: 86400000   # 1 day in ms

# SendGrid configuration
sendgrid:
  api:
    key: ${SENDGRID_API_KEY}

app:
  client:
    url: https://expense-tracker-xi-beige.vercel.app
  api:
    url: https://expense-tracker-github-hkcmdtbra4aacach.canadacentral-01.azurewebsites.net
