deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: java-app
        path: java-app  # ✅ force downloaded contents into this folder

    - name: Debug - List downloaded files
      run: |
        echo "📁 Downloaded contents:"
        ls -R java-app

    - name: Rename JAR for deployment
      run: |
        JAR_FILE=$(find java-app -name "*.jar" | head -n 1)
        echo "Found: $JAR_FILE"
        mv "$JAR_FILE" app.jar

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_51237B1AF0F847729491DC213AE3B570 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_470B561F8BD047E4B15E7298AD89DC65 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3198777CC0CD4D6FB80FCA399558A183 }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'expense-tracker-github'
        slot-name: 'Production'
        package: app.jar
